<?php

//Texte des bandeaux
$tt_bandeau_titre='Se Trouver &agrave; l\'Universit&eacute; de Strasbourg';

$tt_bandeau_pied='Universit&eacute; de Strasbourg - Cr&eacute;ation : Guilhem BORGHESI - 2008';

//texte des boutons dans sous_bandeau
$tt_bouton_accueil='Accueil';
$tt_bouton_exemple='Exemple';
$tt_bouton_contact='Contact';
$tt_bouton_versions='Versions';
$tt_bouton_sources='Sources';
$tt_bouton_apropos='A propos';
$tt_bouton_intranet='Intranet';

//Texte de index.php
$tt_index_presentation='<p><b>A quoi sert STUdS ?</b></p><p>A faire des sondages pour que vous puissiez trouver une date de r&eacute;union qui convienne &agrave; toutes les personnes concern&eacute;es. <br>Vous pouvez &eacute;galement utiliser STUdS pour d&eacute;terminer &agrave; plusieurs un choix quelconque comme un lieu de RV, un th&egrave;me de r&eacute;union ou la marque de votre prochaine machine &agrave; caf&eacute;.</p>'."\n".'<br>'."\n";

$tt_index_bouton='<b>Cr&eacute;er un sondage</b>';

?>
