<?php

//Texte des bandeaux
$tt_bandeau_titre='Se Trouver &agrave; l\'Universit&eacute; de Strasbourg';
$tt_bandeau_titre_infos='Cr&eacute;ation de sondage (1 sur 2)';
$tt_bandeau_titre_date='Choix des dates (2 sur 2)';
$tt_bandeau_titre_autre='Choix des sujets (2 sur 2)';
$tt_bandeau_titre_admin='Administrateur de la base';
$tt_bandeau_titre_contact='Nous contacter';
$tt_bandeau_titre_version='Les diff&eacute;rentes versions et les am&eacute;liorations pr&eacute;vues';
$tt_bandeau_titre_erreur='Erreur !';
$tt_bandeau_titre_apropos='Informations g&eacute;n&eacute;rales';
$tt_bandeau_pied='Universit&eacute; de Strasbourg - Cr&eacute;ation : Guilhem BORGHESI - 2008';

//texte des boutons dans sous_bandeau
$tt_bouton_accueil='Accueil';
$tt_bouton_exemple='Exemple';
$tt_bouton_contact='Contact';
$tt_bouton_versions='Versions';
$tt_bouton_sources='Sources';
$tt_bouton_apropos='A propos';
$tt_bouton_intranet='Intranet';
$tt_bouton_historique='Historique';
$tt_bouton_retour='Retour';

//Texte de index.php
$tt_index_presentation='<p><b>A quoi sert STUdS ?</b></p><p>A faire des sondages pour que vous puissiez trouver une date de r&eacute;union qui convienne &agrave; toutes les personnes concern&eacute;es. <br>Vous pouvez &eacute;galement utiliser STUdS pour d&eacute;terminer &agrave; plusieurs un choix quelconque comme un lieu de RV, un th&egrave;me de r&eacute;union ou la marque de votre prochaine machine &agrave; caf&eacute;.</p>'."\n".'<br>'."\n";
$tt_index_bouton='<b>Cr&eacute;er un sondage</b>';

//texte de infos_sondage.php
$tt_infos_presentation='<br>Vous avez choisi de cr&eacute;er un nouveau sondage !<br> Merci de remplir les champs obligatoires.<br><br>'."\n";

?>
